name: ESLint

on:
  pull_request:
    types:
    - opened
    - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Run Lint
      run: |
        yarn
        yarn lint
      env:
        CI: true
